version: '3.9'

services:
  db:
    image: bitnami/postgresql:latest
    container_name: ubatuba-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ubatuba
      POSTGRES_PASSWORD: ubatuba
      POSTGRES_DB: ubatuba-events-tracker
    volumes:
      - pgdata:/bitnami/postgresql
    networks:
      - ubatuba-net

  api:
    build:
      context: ./apps/api
      dockerfile: ../../docker/api/Dockerfile
    container_name: ubatuba-api
    ports:
      - "8000:8000"
    env_file:
      - ./apps/api/.env
    volumes:
      - ./apps/api:/app/api
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - ubatuba-net
    command: >
      sh -c "alembic upgrade head &&
             uvicorn src.main:app --host 0.0.0.0 --port 8000"

  web:
    build:
      dockerfile: ./docker/web/Dockerfile
    container_name: ubatuba-web
    ports:
      - "3000:3000"
    env_file:
      - ./apps/web/.env
    volumes:
      - ./apps/web:/app/web
    depends_on:
      - api
    restart: unless-stopped
    command: node apps/web/server.js
    
volumes:
  pgdata:

networks:
  ubatuba-net:
    driver: bridge
