version: '3.7'

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ubatuba
      - POSTGRES_PASSWORD=ubatuba
      - POSTGRES_DB=ubatuba-events-tracker